# Generated by Django 3.1.7 on 2021-03-16 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_job_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='staff_member',
        ),
    ]
