# Generated by Django 3.1.7 on 2021-03-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
