# Generated by Django 3.1.7 on 2021-03-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='birthdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
