# Generated by Django 3.1.7 on 2021-03-16 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_remove_job_staff_member'),
        ('access_control', '0003_auto_20210316_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.job'),
        ),
    ]
